version: "3.9"

services:
  simpleapplyapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpleapplyapi
    restart: always
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
